feat: 6.2.14

diff --git a/.github/workflows/quartz64.yml b/.github/workflows/quartz64.yml
--- a/.github/workflows/quartz64.yml
+++ b/.github/workflows/quartz64.yml
@@ -13,12 +13,15 @@ jobs:
         shell: sh
         working-directory: /dev/shm
     env:
-      # https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/?h=linux-rolling-stable
-      linux_version: "6.2.10"
       uboot_branch: "v2022.07-dietpi"
       CROSS_COMPILE: "aarch64-linux-gnu-"
       ARCH: "arm64"
     steps:
+      - name: Apt update for 'gh act'
+        run: "{ sudo apt-get -q update; }"
+      # https://github.com/hendrikmuhs/ccache-action
+      - name: ccache
+        uses: hendrikmuhs/ccache-action@v1.2
       # https://github.com/actions/setup-python/tags
       - uses: actions/setup-python@v4
         with:
@@ -29,11 +32,11 @@ jobs:
           { python3 -m pip install --no-cache-dir -U pip setuptools wheel; python3 -m pip install --no-cache-dir -U pyelftools; } &
           { sudo apt-get -q update; sudo DEBIAN_FRONTEND=noninteractive apt-get --no-install-recommends -qq install make gcc libc6-dev flex bison gcc-aarch64-linux-gnu bc libssl-dev swig; } &
           { curl -fO "https://gitlab.com/MichaIng/u-boot/-/archive/$uboot_branch/u-boot-$uboot_branch.tar.bz2"; tar xf "u-boot-$uboot_branch.tar.bz2"; rm "u-boot-$uboot_branch.tar.bz2"; } &
-          { curl -fO "https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/snapshot/linux-$linux_version.tar.gz"; tar xf "linux-$linux_version.tar.gz"; rm "linux-$linux_version.tar.gz"; } &
+          { curl -fO "https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/snapshot/linux-rolling-stable.tar.gz"; tar xf "linux-rolling-stable.tar.gz"; rm "linux-rolling-stable.tar.gz"; } &
           wait
           curl -sSfo "u-boot-$uboot_branch/u-boot-spl-ddr.bin" 'https://raw.githubusercontent.com/JeffyCN/rockchip_mirrors/rkbin/bin/rk35/rk3568_ddr_1560MHz_v1.13.bin' &
           curl -sSfo "u-boot-$uboot_branch/bl31.elf" 'https://raw.githubusercontent.com/JeffyCN/rockchip_mirrors/6186deb/bin/rk35/rk3568_bl31_v1.28.elf' &
-          curl -sSfo "linux-$linux_version/arch/arm64/configs/quartz64_defconfig" "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/${GITHUB_REF#refs/heads/}/.build/images/Quartz64/quartz64_defconfig" &
+          curl -sSfo "linux-rolling-stable/arch/arm64/configs/quartz64_defconfig" "https://raw.githubusercontent.com/$GITHUB_REPOSITORY_OWNER/DietPi/$GITHUB_REF_NAME/.build/images/Quartz64/quartz64_defconfig" &
           rm -Rf firmware-quartz64a/DEBIAN firmware-quartz64a/boot/extlinux firmware-quartz64a/lib/firmware/brcm
           mkdir -p firmware-quartz64a/DEBIAN firmware-quartz64a/boot/extlinux firmware-quartz64a/lib/firmware/brcm
           rm -Rf firmware-quartz64b/DEBIAN firmware-quartz64b/boot/extlinux firmware-quartz64b/lib/firmware/brcm
@@ -44,6 +47,7 @@ jobs:
       - name: Build U-Boot
         run: |
           export BL31='bl31.elf'
+          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
           cd "u-boot-$uboot_branch"
           make quartz64-a-rk3566_defconfig
           make -j$(nproc)
@@ -58,7 +62,8 @@ jobs:
           rm -R "u-boot-$uboot_branch"
       - name: Build Linux
         run: |
-          cd "linux-$linux_version"
+          cd "linux-rolling-stable"
+          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
           make quartz64_defconfig
           make -j$(nproc)
           cp arch/arm64/boot/Image.gz ../firmware-quartz64a/boot/vmlinuz
@@ -74,7 +79,8 @@ jobs:
           cp -R firmware-quartz64a/lib/modules firmware-soquartz/lib/
       - name: Build package
         run: |
-          rm -R "linux-$linux_version"
+          version=$(mawk '/^VERSION =/{a=$3};/^PATCHLEVEL =/{b=$3};/^SUBLEVEL/{c=$3};END{print a"."b"."c}' linux-rolling-stable/Makefile)
+          rm -R "linux-rolling-stable"
           curl -sSfO 'https://dietpi.com/downloads/binaries/firmware-quartz64a.deb' &
           curl -sSfo firmware-quartz64b/lib/firmware/brcm/brcmfmac43456-sdio.bin 'https://raw.githubusercontent.com/armbian/firmware/master/brcm/brcmfmac43456-sdio.bin' &
           curl -sSfo firmware-quartz64b/lib/firmware/brcm/brcmfmac43456-sdio.clm_blob 'https://raw.githubusercontent.com/armbian/firmware/master/brcm/brcmfmac43456-sdio.clm_blob' &
@@ -88,14 +94,6 @@ jobs:
           echo "New kernel version is:       $version"
           [ "$version-dietpi$cur_suffix" = "$cur_version" ] && version="$version-dietpi$((cur_suffix+1))" || version="$version-dietpi1"
           echo "New package version will be: $version"
-          rm firmware-quartz64a.deb
-          suffix=${version#*-dietpi}
-          if [ "$version" = "$linux_version-dietpi$suffix" ]
-          then
-              version="$linux_version-dietpi$((suffix+1))"
-          else
-              version="$linux_version-dietpi1"
-          fi
           cp firmware-quartz64a/lib/firmware/brcm/brcmfmac43455-sdio.txt firmware-soquartz/lib/firmware/brcm/
           cat << '_EOF_' > firmware-quartz64a/boot/extlinux/extlinux.conf
           label DietPi
@@ -118,31 +116,31 @@ jobs:
           then
           echo "Flashing to detected boot drive: $BOOT_DRIVE"
           else
-          	echo 'ERROR: Unable to detect boot drive, aborting U-Boot flashing'
-          	exit 1
+            echo 'ERROR: Unable to detect boot drive, aborting U-Boot flashing'
+            exit 1
           fi
           dd 'if=/boot/u-boot.bin' "of=$BOOT_DRIVE" seek=64 conv=fdatasync
           if grep -q 'root=/dev/mmcblk0p1' /boot/extlinux/extlinux.conf
           then
           	echo 'Setting root filesystem entries in extlinux.conf'
-          	ROOT_PARTUUID=$(findmnt -Ufnro PARTUUID -M /)
-          	if [ $ROOT_PARTUUID ]
-          	then
-          		echo "Setting root filessystem PARTUUID: $ROOT_PARTUUID"
-          	else
-          		echo 'ERROR: Unable to detect root filessystem PARTUUID, aborting'
-          		exit 1
-          	fi
-          	sed -i "s|root=/dev/mmcblk0p1|root=PARTUUID=$ROOT_PARTUUID|" /boot/extlinux/extlinux.conf
-          	ROOT_FSTYPE=$(findmnt -Ufnro FSTYPE -M /)
-          	if [ $ROOT_FSTYPE ]
-          	then
-          		echo "Setting root filesystem type: $ROOT_FSTYPE"
-          	else
-          		echo 'ERROR: Unable to detect root filesystem type, aborting'
-          		exit 1
-          		fi
-          	sed -i "s|rootfstype=ext4|rootfstype=$ROOT_FSTYPE|" /boot/extlinux/extlinux.conf
+            ROOT_PARTUUID=$(findmnt -Ufnro PARTUUID -M /)
+            if [ $ROOT_PARTUUID ]
+            then
+              echo "Setting root filessystem PARTUUID: $ROOT_PARTUUID"
+            else
+              echo 'ERROR: Unable to detect root filessystem PARTUUID, aborting'
+              exit 1
+            fi
+            sed -i "s|root=/dev/mmcblk0p1|root=PARTUUID=$ROOT_PARTUUID|" /boot/extlinux/extlinux.conf
+            ROOT_FSTYPE=$(findmnt -Ufnro FSTYPE -M /)
+            if [ $ROOT_FSTYPE ]
+            then
+              echo "Setting root filesystem type: $ROOT_FSTYPE"
+            else
+              echo 'ERROR: Unable to detect root filesystem type, aborting'
+              exit 1
+              fi
+            sed -i "s|rootfstype=ext4|rootfstype=$ROOT_FSTYPE|" /boot/extlinux/extlinux.conf
           fi
           exit 0
           _EOF_
